# Generated by Django 4.2.4 on 2024-10-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('data', models.JSONField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicedetails')),
            ],
        ),
    ]
