# Generated by Django 4.2.4 on 2024-10-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=45)),
                ('device_token', models.CharField(max_length=100, unique=True)),
                ('hardware_version', models.CharField(blank=True, max_length=10, null=True)),
                ('software_version', models.CharField(blank=True, max_length=10, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('mqtt', 'MQTT'), ('http', 'HTTP')], max_length=10)),
                ('pub_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('api_path', models.CharField(blank=True, max_length=100, null=True)),
                ('device_status', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
